# Generated by Django 5.1.6 on 2026-07-31 07:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengeTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title_uz', models.CharField(max_length=255)),
                ('description_uz', models.TextField(blank=True)),
                ('dimension', models.CharField(choices=[('ruhiy', 'Ruhiy'), ('jismoniy', 'Jismoniy'), ('moliyaviy', 'Moliyaviy'), ('ijtimoiy', 'Ijtimoiy'), ('ilmiy', 'Ilmiy')], max_length=16)),
                ('duration_days', models.IntegerField()),
                ('schedule', models.JSONField(default=dict)),
                ('is_builtin', models.BooleanField(default=False)),
                ('slug', models.SlugField(max_length=64, unique=True)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('dimension', models.CharField(choices=[('ruhiy', 'Ruhiy'), ('jismoniy', 'Jismoniy'), ('moliyaviy', 'Moliyaviy'), ('ijtimoiy', 'Ijtimoiy'), ('ilmiy', 'Ilmiy')], max_length=16)),
                ('priority', models.CharField(choices=[('high', 'Yuqori'), ('medium', "O'rta"), ('low', 'Past')], default='medium', max_length=8)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Faol'), ('done', 'Bajarilgan'), ('archived', 'Arxivlangan')], default='active', max_length=16)),
                ('source_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goals', to='goals.challengetemplate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Faol'), ('done', 'Bajarilgan'), ('archived', 'Arxivlangan')], default='active', max_length=16)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='goals.goal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('priority', models.CharField(choices=[('high', 'Yuqori'), ('medium', "O'rta"), ('low', 'Past')], default='medium', max_length=8)),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('done', 'Bajarilgan'), ('skipped', "O'tkazib yuborilgan")], default='pending', max_length=16)),
                ('sort_order', models.IntegerField(default=0)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('goal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='goals.goal')),
                ('milestone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='goals.milestone')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='goal',
            index=models.Index(fields=['user', 'status'], name='goals_goal_user_id_7ad9fc_idx'),
        ),
        migrations.AddIndex(
            model_name='goal',
            index=models.Index(fields=['user', 'dimension'], name='goals_goal_user_id_4271e1_idx'),
        ),
        migrations.AddIndex(
            model_name='milestone',
            index=models.Index(fields=['user', 'goal'], name='goals_miles_user_id_53c0f1_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['user', 'date'], name='goals_task_user_id_edf29f_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['user', 'status'], name='goals_task_user_id_fc0ca5_idx'),
        ),
    ]
