# Generated by Django 5.1.6 on 2026-07-31 07:32

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name_uz', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('income', 'Kirim'), ('expense', 'Chiqim')], max_length=8)),
                ('dimension', models.CharField(blank=True, choices=[('ruhiy', 'Ruhiy'), ('jismoniy', 'Jismoniy'), ('moliyaviy', 'Moliyaviy'), ('ijtimoiy', 'Ijtimoiy'), ('ilmiy', 'Ilmiy')], max_length=16, null=True)),
                ('icon', models.CharField(blank=True, max_length=64)),
                ('is_sadaqa', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(default='UZS', max_length=3)),
                ('type', models.CharField(choices=[('income', 'Kirim'), ('expense', 'Chiqim')], max_length=8)),
                ('note', models.TextField(blank=True)),
                ('date', models.DateField()),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='finance.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-date', '-created_at'),
            },
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['user', 'type'], name='finance_cat_user_id_0d1be8_idx'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('user', 'name_uz', 'type'), name='uniq_category_per_user_name_type'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'date'], name='finance_tra_user_id_3294c0_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'type'], name='finance_tra_user_id_35643f_idx'),
        ),
    ]
