# Generated by Django 5.1.6 on 2026-07-31 07:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('name', models.CharField(choices=[('bomdod', 'Bomdod'), ('peshin', 'Peshin'), ('asr', 'Asr'), ('shom', 'Shom'), ('xufton', 'Xufton')], max_length=16)),
                ('status', models.CharField(choices=[('done', "O'qilgan"), ('missed', 'Qazo'), ('excused', 'Uzrli'), ('late', 'Kech')], max_length=16)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('date', 'id'),
                'indexes': [models.Index(fields=['user', 'date'], name='prayers_pra_user_id_8b786e_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'date', 'name'), name='uniq_prayer_per_user_date_name')],
            },
        ),
    ]
