# Generated by Django 5.1.6 on 2026-07-31 07:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_lat', models.FloatField(blank=True, null=True)),
                ('location_lng', models.FloatField(blank=True, null=True)),
                ('location_name', models.CharField(blank=True, max_length=120)),
                ('calc_method', models.CharField(choices=[('MuslimWorldLeague', 'Muslim World League'), ('UmmAlQura', 'Umm al-Qura'), ('Egyptian', 'Egyptian'), ('Karachi', 'Karachi'), ('Tehran', 'Tehran'), ('Dubai', 'Dubai'), ('Qatar', 'Qatar'), ('Kuwait', 'Kuwait'), ('Singapore', 'Singapore'), ('Turkey', 'Turkey'), ('NorthAmerica', 'North America')], default='MuslimWorldLeague', max_length=32)),
                ('asr_madhab', models.CharField(choices=[('Hanafi', 'Hanafi'), ('Shafi', 'Shafi')], default='Hanafi', max_length=16)),
                ('prayer_offsets', models.JSONField(blank=True, default=dict)),
                ('hide_sadaqa', models.BooleanField(default=False)),
                ('notif_prefs', models.JSONField(blank=True, default=dict)),
                ('onboarded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_profile',
            },
        ),
    ]
