# Generated by Django 5.1.6 on 2026-07-31 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='calc_method',
            field=models.CharField(choices=[('MuslimWorldLeague', 'Muslim World League'), ('UmmAlQura', 'Umm al-Qura'), ('Egyptian', 'Egyptian'), ('Karachi', 'Karachi'), ('Dubai', 'Dubai'), ('Qatar', 'Qatar'), ('Kuwait', 'Kuwait'), ('Singapore', 'Singapore'), ('MoonsightingCommittee', 'Moonsighting Committee'), ('NorthAmerica', 'North America')], default='MuslimWorldLeague', max_length=32),
        ),
    ]
