# Generated by Django 5.1.6 on 2026-07-31 07:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('week_start', models.DateField()),
                ('answers', models.JSONField(default=dict)),
                ('mizan_score', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-week_start',),
                'indexes': [models.Index(fields=['user', 'week_start'], name='mizan_revie_user_id_b9bd06_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'week_start'), name='uniq_review_per_user_week')],
            },
        ),
    ]
